@startuml

component App

component Navigation
component Route
component PrivateRoute

note right
	Special route that
	checks authentication
	in AppState
end note

component LoginPage
agent AppState
agent AuthService
package ApiServices

note right
	Any API service, which
	provide data or reset auth
	when token expired.

	Usually, AppState passed in
	services inside pages (when
	service instance created).
end note

package Pages

App --> Navigation
Navigation --> Route
Navigation --> PrivateRoute
Route --> LoginPage
PrivateRoute --> Pages


LoginPage .. AuthService

PrivateRoute .. AppState: Check auth
LoginPage . AppState: Set auth
AppState .. ApiServices: Reset auth


@enduml
