@startuml

component App

component Navigation
component Route
component PrivateRoute

note top
	Special route that:
	- Checks authentication
	- Checks valid roles
end note

component LoginPage
agent AppState
agent AuthService
package ApiServices

note top
	Any API service, which
	provide data or reset auth
	when token expired.

	Usually, AppState.clearToken()
	passed in services inside pages
	(when service instance created).
end note

package Pages

App --> Navigation
Navigation --> Route
Navigation -> PrivateRoute
Route --> LoginPage
PrivateRoute -> Pages


LoginPage .. AuthService

PrivateRoute .. AppState: Check auth
LoginPage . AppState: Set auth
AppState . ApiServices: Reset auth


@enduml
