@startuml

component App
component Navigation
component Route
component PrivateRoute
component LoginPage
component TemplateGenerator

note top
	Container for:

	__Library__ - List of blocks
	that can be customized
	and added to the template

	__Template__ - List of configured
	and added blocks from which
	the template will be created.
end note

component Library
component Template
component Document
component TemplateList
component DocumentList
component AttachDocument

note right
	Used for attaching
	document to current user
end note

package Blocks

note right
	Blocks are the components
	from which a document
	template is assembled.
end note

agent BlockService

note right
	Helps to render blocks.
	Provides block instances,
	default props and config fields.
end note

App -- Navigation
Navigation -> Route
Route -> LoginPage
Navigation --> PrivateRoute


PrivateRoute --> TemplateGenerator
TemplateGenerator --> Library
TemplateGenerator --> Template

PrivateRoute ---> Document
PrivateRoute ---> TemplateList
PrivateRoute ---> DocumentList
PrivateRoute -> AttachDocument

Library .. BlockService
Template .. BlockService
Document .. BlockService
BlockService .. Blocks


@enduml
